#!/bin/bash

# Replace px (pixels) by rem (M width at root element) for adaptive
# designs. Assume that 1rem == 16px. Changes are stored in separate
# file with .px2rem extension.

for I in "$@"
do
 perl -p -e 's/(-?[0-9.]+)px/($1\/16)."rem\/*${1}px*\/"/ge' <"$I" >"$I.px2rem"
done
